language: python
python:
  - "2.7"
env:
  - TEST_RUN="FULL"
  - TEST_RUN="COVER"
# command to install dependencies
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -q -y gfortran libhdf5-serial-dev libnetcdf-dev liblapack-dev libatlas-dev
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes conda
install:
  - conda create --yes -q -n pyenv mkl python=2.7 numpy=1.9.1 scipy=0.14.0 nose=1.3.4
  - source activate pyenv
  - conda install --yes python=$TRAVIS_PYTHON_VERSION cython biopython matplotlib networkx netcdf4
  - pip install package/
  - pip install testsuite/
  - pip install coveralls
  - chmod +x testsuite/MDAnalysisTests/mda_nosetests
# command to run tests
script:
  - if [[ $TEST_RUN == "FULL" ]]; then ./testsuite/MDAnalysisTests/mda_nosetests -v --with-memleak --processes=2 --process-timeout=120; fi
  - if [[ $TEST_RUN == "COVER" ]]; then nosetests -v --with-coverage --cover-package MDAnalysis; fi
after_success:
  - if [[ $TEST_RUN == "COVER" ]]; then coveralls; fi